### ISSUE TITLE
build: add .zenodo.json for valid metadata crawling

### ISSUE THREAD

**Issue by SebastianDD** [ieeh-tu-dresden/powerfactory-utils#17]
* create initial .zenodo.json file
```
{
    "description": "This application is intended to use for an external usage ('engine mode') of the power flow calculation program [DIgSILENT PowerFactory](https://www.digsilent.de/de/powerfactory.html). Therefore, the Python-PowerFactory-API, provided by the company, is utilized.", 
    "title": "Powerfactory Utils - A toolbox for Python based control of DIgSILENT PowerFactory", 
    "version": "1.0.0", 
    "upload_type": "software", 
    "keywords": [
        "Toolbox", 
        "PowerFactory", 
        "JSON", 
        "Python", 
        "Grid Model"
    ], 
    "publication_date": "2022-09-19", 
    "creators": [
        {
            "name": "Institute of Electrical Power Systems and High Voltage Engineering - TU Dresden"
        }
    ], 
    "license": "BSD-3-Clause",
    "access_right": "open", 
    "related_identifiers": [
        {
            "scheme": "url", 
            "identifier": "https://github.com/ieeh-tu-dresden/powerfactory-utils/tree/1.0.0", 
            "relation": "isSupplementTo"
        }, 
        {
            "scheme": "doi", 
            "identifier": "10.5281/zenodo.7074968", 
            "relation": "isVersionOf"
        }
    ]
}
```

* for each release automatically update the .zenodo.json file
  * description: --> changelog
  * version
  * publication date:
  * identifier:

**Comment by sasanjac** [comment]
1. I'd prefer if the description did not change with every new release.
2. What do we have to update in the `related_identifiers` field? Where do we get the new doi?

**Comment by SebastianDD** [comment]
1. You're right. We shall leave the description blank.
2. We have to change only the `identifier` for the `url`. The doi identifier is fix.
3. if we **want** we can add "note": "Name of contributers (@ github_name)"

**Comment by SebastianDD** [comment]
> 1. I'd prefer if the description did not change with every new release.
> 2. What do we have to update in the `related_identifiers` field? Where do we get the new doi?

1. You're right. We shall leave the description blank.
2. We have to change only the `identifier` for the `url`. The doi identifier is fix.
3. if we **want** we can add "note": "Name of contributers (@ github_name)"

**Comment by SebastianDD** [comment]
Proposal for description

`This application is intended to use for an external usage ('engine mode') of the power flow calculation program DIgSILENT PowerFactory. Therefore, the Python-PowerFactory-API, provided by the company, is utilized.`
