### ISSUE TITLE
feat: request user input to specify PF version and path

### ISSUE THREAD

**Issue by SebastianDD** [ieeh-tu-dresden/powerfactory-utils#66]
The version of PowerFactory is hardcoded to 2022 SP2.
Use this only as default path and check via registry entry?

Give the user the possibility to set an optional user specific path to ther actual powerfactory directory.
--> adapt also example and documentation

**Comment by sasanjac** [comment]
Thats already possible, `Exporter` accepts the following parameters, only their defaults are hardcoded:
- `powerfactory_path`
- `powerfactory_version`

Im going to close this issue in favor of a complete overhaul of the PowerFactory type registry, in which we can define and test the data model of multiple PF versions. In the same, we can implement a detection of all installed PF versions, show the user which ones are compatible with the used python version and let the user choose a PF installation.
