### ISSUE TITLE
fix: export of external and internal controller data 

### ISSUE THREAD

**Issue by FiedLa** [ieeh-tu-dresden/powerfactory-utils#71]
**Describe the bug**
I have noticed that the data of the external and internal controller is not exported in the steadystate_case.json (for a special customer in the example network). 

**To Reproduce**
To see the exact customer where the error occurs:
1. Go to PowerFactory and click on 'StatGenerator_2' (and then on its external controller) (cosphi(P)-characteristic)
![grafik](https://user-images.githubusercontent.com/122098671/212362642-4bbbb991-8e40-4e73-8c82-c1901790db00.png)
![grafik](https://user-images.githubusercontent.com/122098671/212362269-49b4c38a-4a76-4c06-9200-015480a15727.png)
2. Go to the mentioned .json-file (HV_8_Bus_steadystate_case.json)
![grafik](https://user-images.githubusercontent.com/122098671/212362892-0529fa62-0db1-481c-a5f5-4813232de1d3.png)

**Comment by SebastianDD** [comment]
Thanks for reporting. This topic is already addressed in issue #9
